// [MESSAGE]
export const MESSAGE_SEND = 'MESSAGE_SEND';
export const MESSAGE_EDIT = 'MESSAGE_EDIT';
export const MESSAGE_TEXT_FLUSH = 'MESSAGE_TEXT_FLUSH';
export const MESSAGE_COLLECTION_LOAD_SUCCESS = 'MESSAGE_COLLECTION_LOAD_SUCCESS';

// [ROOM]
export const ROOM_SEARCH = 'ROOM_SEARCH';
export const ROOM_SELECT = 'ROOM_SELECT';
export const ROOM_COLLECTION_LOAD_SUCCESS = 'ROOM_COLLECTION_LOAD_SUCCESS';
export const ROOM_ONLINE_UPDATE = 'ROOM_ONLINE_UPDATE';

// [USER}
export const USER_AUTHORIZE_SUCCESS = 'USER_AUTHORIZE_SUCCESS';
export const USER_ONLINE_UPDATE = 'USER_ONLINE_UPDATE';
